---
title: "Supply Plan"
author: "Kristine Lan"
date: "2017/8/23"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This R Markdown document is made interactive using Shiny. The data is from the COP17 supply plan.

To learn more, see [Interactive Documents](http://rmarkdown.rstudio.com/authoring_shiny.html).

```{r include = FALSE}
library(shiny)
library(ggplot2)
library(plotly)
library(RJSONIO)
library(magrittr)
library(leaflet)
library(rgdal)
library(rsconnect) #publish
```


```{r echo=FALSE, warning=FALSE}

master = read.csv(url("http://www-personal.umich.edu/~lankrist/COP17_master_verbose.csv"))
master$Unit.price = as.numeric(as.character(master$Unit.price))
master$Quantity = as.numeric(as.character(master$Quantity))
#top two lines generate Warnings
colnames(master)[6] = "Item"

# m = master[master$Country != "Vietnam" ,]
# m = m[m$Country != "Burundi",]; m = m[m$Country != "South Sudan",]
# master = m[m$Country != "Ukraine",] 

arv2 = master[grepl("line",master$Category), ]
arv3 = master[grepl("ARV", master$Category),]
arv_ = rbind(arv2, arv3); 
arv = aggregate(Quantity~Item, data = arv_,FUN = sum)
arvh = arv[order(-arv$Quantity),]
arv1=arv_[arv_$Item %in% arvh[1:10,]$Item,]



g = ggplot(arv1, aes(x = Country, y = Quantity, fill = Item))
g1 = g+geom_bar(stat = "Identity")

f = ggplot(arv1, aes(x = Country, y = Unit.price, colour = Item, size = Quantity))
f1 = f + geom_point()

```

## Top 10 ARV Procurement Quantity by Country

```{r echo=FALSE}
#shiny
ui <- fluidPage(plotlyOutput("distPlot"))

server <- function(input, output) {
  output$distPlot <- renderPlotly({
    g1 + theme(axis.text.x = element_text(angle = 45, hjust = 1))
  })
}

shinyApp(ui, server)

```

## Top 10 ARV Procurement Unit Price by Country

```{r echo=FALSE}
#shiny
ui <- fluidPage(plotlyOutput("distPlot"))

server <- function(input, output) {
  output$distPlot <- renderPlotly({
    f1 + theme(axis.text.x = element_text(angle = 45, hjust = 1))
  })
}

shinyApp(ui, server)

```

```{r echo=FALSE, warning=FALSE}
#RTK
rtk = master[master$Category == "RTKs", ]
rtk_=aggregate(Quantity~Item, data = rtk,FUN = sum)
rtkh = rtk_[order(-rtk_$Quantity),]

rtk1 = rtk[rtk$Item %in% rtkh[1:10,]$Item,]
rtk2=rtk1[rtk1$Unit.price<150,]

f4 = ggplot(rtk2, aes(x = Quantity, y = Unit.price, colour = Item))
f5 = f4 + geom_point()+labs(caption = "(Excluded Outliers for Unit Price)")

```

## RTK Quantity VS Unit Price

```{r echo=FALSE}
#shiny
ui <- fluidPage(plotlyOutput("distPlot"))

server <- function(input, output) {
  output$distPlot <- renderPlotly({
    f5
  })
}

shinyApp(ui, server)

```


```{r echo=FALSE, warning=FALSE}
med = master[master$Category == "Essential Meds", ]
med_ = aggregate(Quantity~Item, data = med,FUN = sum)
medh = med_[order(-med_$Quantity),]

med1 = med[med$Item %in% medh[1:10,]$Item,]
med2=med1[med1$Unit.price<150,]

f6 = ggplot(med2, aes(x = Quantity, y = Unit.price, colour = Item))
f7 = f6 + geom_point()+labs(caption = "(Excluded Outliers for Unit Price)")

```

## Essential Medicine Quantity VS Unit Price

```{r echo=FALSE}
#shiny
ui <- fluidPage(plotlyOutput("distPlot"))

server <- function(input, output) {
  output$distPlot <- renderPlotly({
    f7
  })
}

shinyApp(ui, server)

```


